POST  http://localhost:3001/info HTTP/1.1
content-type: application/json

{
  "name": "Eyeline",
  "email":"email@mail.com",
  "address": "Address",
  "phonenumber": 5242342,
  "workinghours":"from 08:00 to 22:00"
}